accent = "#e55812"
cursor = "#a4b4b4"
foreground = "#ffffff"
background = "#000000"
selection_foreground = "#1e1e2e"
selection_background = "#f5e0dc"

color0 = "#333333"
color1 = "#e19e74"
color2 = "#ffc107"
color3 = "#c6c4b0"
color4 = "#e68e0d"
color5 = "#8a8575"
color6 = "#bebebe"
color7 = "#bebebe"
color8 = "#8a8a8d"
color9 = "#984b1e"
color10 = "#ffc107"
color11 = "#8f4445"
color12 = "#f59e0b"
color13 = "#b3adad"
color14 = "#eaeaea"
color15 = "#ffffff"
